application:
  port: 8000
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 9009
  username: "postgres"
  password: "password"
  database_name: "newsletter"
