application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
email_client:
  base_url: "http://127.0.0.1:7001"
  sender_email: "test@gmail.com"
  authorization_token: "my-secrte-token"
